import { useState } from "react";

import { EmailPreview } from "./EmailPreview";

export function EmailList({ emails }) {
  console.log(emails);
  return (
    <section className="email-list">
      <div>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
        <p>sdaasdf</p>
      </div>
    </section>
  );
}
